# Generated by Django 4.0.4 on 2022-05-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
