# Generated by Django 4.0.4 on 2022-05-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognizer', '0002_person_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='count',
        ),
    ]
